### ISSUE TITLE
ng start fails

### ISSUE THREAD

**Issue by xadhix** [tholthamizh/tholthamizhpadhangal#4]
$ ng start
C:\Users\user\AppData\Roaming\npm\node_modules\angular-cli\bin\ng:7
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by tholthamizh** [comment]
Have you installed latest Node and NPM?

**Comment by tholthamizh** [comment]
Please install latest version of Node and NPM.
